### ISSUE TITLE
Hello thankyou for the repository I tried to evaluate using provided pretrained model but it returns all zero like this. Any suggestion please?

### ISSUE THREAD

**Issue by Nure123** [facebookresearch/adaptive_teacher#17]
![result](https://user-images.githubusercontent.com/107245714/173034088-2070cb92-3068-4dfb-b9a1-875656e8e3b1.png)

**Comment by yujheli** [comment]
We haven't provided the local pre-trained weights yet. Which weight were you loading?

**Comment by Nure123** [comment]
I used The pretrained model provided on this link 
[link](https://drive.google.com/drive/folders/17p8oYjhmoA77_hyVZq4WLJezsUiSZhdi?usp=sharing)

**Comment by yujheli** [comment]
@Nure123 The pre-trained weights are for the d2go prod codes at: https://github.com/facebookresearch/adaptive_teacher/tree/main/prod_lib
You will need to align the keys

**Comment by yujheli** [comment]
@Nure123 The pretrained models are updated for Clipart. You can load these weights again to see if you still have issues.

**Comment by ad45675** [comment]
> ![result](https://user-images.githubusercontent.com/107245714/173034088-2070cb92-3068-4dfb-b9a1-875656e8e3b1.png)

hi, i want to ask . how to show the per-category bbox AP result

**Comment by yujheli** [comment]
@ad45675 I usually see the numbers in tensorboard. If you open the tensorboard then you can find AP@50 for each class.

**Comment by ad45675** [comment]
> @ad45675 I usually see the numbers in tensorboard. If you open the tensorboard then you can find AP@50 for each class.

ok, i found it thanks!
