### ISSUE TITLE
Evaluation for each category

### ISSUE THREAD

**Issue by helq2612** [facebookresearch/adaptive_teacher#22]
Hi authors,

Great work! I tried to reproduce the adaptive teacher, but I find the script used to evaluate is only for coco style metrics. Do you have the script to output per category AP so that we can compare with the results in the paper?

Thanks!

**Comment by yujheli** [comment]
@helq2612 Yes, please see the codes at: https://github.com/facebookresearch/adaptive_teacher/blob/main/prod_lib/evaluation/coco_evaluation.py

I haven't migrated to the trainer.py yet you can import this file and replace the one in the original detectron2. This code will report AP50 in the tensorboard
