### ISSUE TITLE
ImportError: cannot import name 'FastRCNNOutputs' from 'detectron2.modeling.roi_heads.fast_rcnn'

### ISSUE THREAD

**Issue by drickzsy** [facebookresearch/adaptive_teacher#3]
There is no FastRCNNOutputs in the detectron installed according to the installation steps, did I install it wrong?

**Comment by yujheli** [comment]
I think if you install the detectron2 correctly, you should be able to load the library.

**Comment by krumo** [comment]
Hi @yujheli, I'm also faced with the same problem. In the https://github.com/facebookresearch/detectron2/commit/11528ce083dc9ff83ee3a8f9086a1ef54d2a402f, the class `FastRCNNOutputs` is removed from `detectron2.modeling.roi_heads.fast_rcnn` So in the the latest version, detectron2 doesn't have this class. I think it would be better if you could consider to provide the version of detectron2 on which this repo is based.

**Comment by yujheli** [comment]
I just found the version of detectron2 I was using is v0.3. I will update the readme.

**Comment by darkhan-s** [comment]
[This seems to solve the issue](https://github.com/facebookresearch/unbiased-teacher/issues/44#issue-993083144)

**Comment by leoliu37** [comment]
This is the problem of detecron2 version, I solve it by installing suitable version in https://github.com/facebookresearch/detectron2/releases
