### ISSUE TITLE
Can adaptive teacher use one-stage detector?

### ISSUE THREAD

**Issue by huanmx** [facebookresearch/adaptive_teacher#34]

**Comment by yujheli** [comment]
I haven't tried it yet. I think if you append the adversarial loss on it maybe it would also work.

**Comment by huanmx** [comment]
Thanks for your reply!
There is another question. Why not use discriminator to get loss_D_img_t in "supervise_target" branch rather than in "domain" branch. In other words, can we discard the "domain" branch and get loss_D_img_t in "supervise_target" branch and loss_D_img_s in "supervise" branch?

**Comment by yujheli** [comment]
@huanmx yeah, I think so. Since the loss is optimized at the same time for each iteration, that should also work.
