### ISSUE TITLE
Question about Figure 4

### ISSUE THREAD

**Issue by tmp12316** [facebookresearch/adaptive_teacher#4]
Thank you for your work. But I have a question about Figure 4 in the main paper.

It seems that with only 10k iterations of the source-only pre-training, the model has achieved around 33.0 mAP, which has significantly outperformed the well-trained source-only results (28.8). Does it mean that the detectron2 implemented FRCNN works better?

**Comment by yujheli** [comment]
The result of high performance reported in the first iteration was after the first update of EMA (with one iteration update using pseudo labels). Though, we also think implementation with detectron2 usually has higher performance.
