### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by GeoffreyChen777** [facebookresearch/adaptive_teacher#44]
Hi, thanks for your work.

https://github.com/facebookresearch/adaptive_teacher/blob/d57d20640ae314a42c43dd82b1c1e26e90fa4b95/adapteacher/data/datasets/cityscapes_foggy.py#L79-L85

Here if we don't close the pool, that may cause a memory leak.

```
pool.close()
````

**Comment by yujheli** [comment]
Thanks for the suggestion. I updated.
