### ISSUE TITLE
Why 2 seperate annotation files?

### ISSUE THREAD

**Issue by victor00070** [facebookresearch/adaptive_teacher#45]
In readme.md, it is instructed to put gtFine folder to both clear and foggy data directories. But foggy images are created from clear ones therefore their annotations should be exactly the same. Indeed, there is only one annotation file in download link for cityscapes. Are we supposed to put exactly same gtFine folder to 2 different places?
Or is it structured like this to train custom datasets? Because unsupervised images dont have to be created synthetically from clean images.
Thanks

**Comment by yujheli** [comment]
Thanks for noting this. Copying the same annotation will make the implementation easier for detectron2.

**Comment by victor00070** [comment]
I will be using a custom dataset and I dont have annotations for target data. Should I add dummy annotations such as bbox: [0,0,0,0] if the model will ignore it anyway @yujheli ?

**Comment by victor00070** [comment]
Thanks, I have some annotated data in target but I will use it only for validation and test. Images without annotations will be used as train.
