### ISSUE TITLE
How to get the AP of each label?

### ISSUE THREAD

**Issue by judyxt** [facebookresearch/adaptive_teacher#59]
I can only get the whole AP(mAP\AP50\AP75) of VOC->Clipart,  but I want to look the AP of each label, is there any tools in the project I ignored ?   Really appreciate you reply!!!

**Comment by yujheli** [comment]
I usually went into the tensorboard to see the AP@50 for each category.

**Comment by judyxt** [comment]
Thank you so much!I got it!
