### ISSUE TITLE
How to train a SourceOnly model or Oracle model?

### ISSUE THREAD

**Issue by Donghuan777** [facebookresearch/adaptive_teacher#62]
Thanks for your work!
Would you tell me how to train a source-only model or oracle model?
And i find BaselineTrainer in 'trainer.py', i guass using it to trian a oracle model, but there is something wrong when use it.
'[Errno 2] No such file or directory: 'dataseed/COCO_supervision.txt''
Looking for your reply!

**Comment by yujheli** [comment]
Training the source-only or oracle model is just using the burn-in (up) stage without entering mutual learning.

**Comment by HarryKang13** [comment]
Thank you very much!
