### ISSUE TITLE
Regarding the Watercolor Dataset Config

### ISSUE THREAD

**Issue by michaelku1** [facebookresearch/adaptive_teacher#8]
Hello, so I am wondering whether there is a specific split file we have to run to obtain the voc split for the watercolor dataset? The burn in training for watercolor only trains on the 7 overlapping classes that span both voc and watercolor. Is that part of the code missing or is it assumed to be done by ourselves.? Many Thanks.

**Comment by yujheli** [comment]
@michaelku1 I put it in the config folder. You can directly run it without revising the code.

**Comment by michaelku1** [comment]
Just saw it, Thanks.
